flake8_task:
  container:
    image: python:3
  setup_script:
    - pip install flake8
  script:
    - flake8

test_task:
  container:
    image: python:3
  setup_script:
    - pip install -r requirements-tests.txt
  script:
    - pytest
